version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/shopper_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db
    working_dir: /app
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopper_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopper_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
